### ISSUE TITLE
ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by jimmon89** [TanninOne/modorganizer-umbrella#19]
**FIRST RUN**

```
Collecting decorator
  Using cached decorator-4.0.10-py2.py3-none-any.whl
Installing collected packages: decorator
Successfully installed decorator
Traceback (most recent call last):
  File "D:\Programs\modorganizer-umbrella\unimake.py", line 239, in <module>
    main()
  File "D:\Programs\modorganizer-umbrella\unimake.py", line 170, in main
    init_config(args)
  File "D:\Programs\modorganizer-umbrella\unimake.py", line 113, in init_config
    config['__environment'] = visual_studio_environment()
  File "D:\Programs\modorganizer-umbrella\unimake.py", line 91, in visual_studio_environment
    key, value = line.split("=", 1)
ValueError: need more than 1 value to unpack
```

**SECOND RUN**

```
Traceback (most recent call last):
  File "D:\Programs\modorganizer-umbrella\unimake.py", line 239, in <module>
    main()
  File "D:\Programs\modorganizer-umbrella\unimake.py", line 170, in main
    init_config(args)
  File "D:\Programs\modorganizer-umbrella\unimake.py", line 113, in init_config
    config['__environment'] = visual_studio_environment()
  File "D:\Programs\modorganizer-umbrella\unimake.py", line 91, in visual_studio_environment
    key, value = line.split("=", 1)
ValueError: need more than 1 value to unpack
```

**OS:** windows 10 64bit home
**VS Version:** 2013 Express
**Config.py** [config.py.txt](https://github.com/TanninOne/modorganizer-umbrella/files/520440/config.py.txt)

no other modifications to the files made besides to config.py

**PREREQUISITES**
**graphviz** _C:\Program Files (x86)\Graphviz2.38\_
**cmake**    _C:\Program Files\Cmake\_
**git**          _D:\Programs\Git\_
**hg**          _C:\Program Files\TortoiseHg\_
**perl**        _C:\StrawberryPerl\_
**ruby**      _C:\Ruby22-x64\_
**svn**        _C:\Program Files\SlikSvn\_
**7z**          _C:\Program Files\7-Zip\_

**Comment by LePresidente** [comment]
Can you verify if this still happens, I have updated umbrella to use VS2015

**Comment by LePresidente** [comment]
This looks like the c++ toolset were not installed.

Probably a better error should be added.

**Comment by LePresidente** [comment]
Closing due to this has been fixed.
