### ISSUE TITLE
Build process fails if PATH key is 'PATH'

### ISSUE THREAD

**Issue by N3X15** [TanninOne/modorganizer-umbrella#4]
I'm trying to run a clean build on Windows 10.
# Operating System Information
- Windows 10 Pro x64
- Python 2.7.10 (32-bit)
- 7za 15.09 beta (from chocolatey)
# PATH capitalization

```
C:\Users\Rob\Documents\Projects\modorganizer>python unimake.py -d build
2015-11-13 19:44:34,217 building dependency graph
Traceback (most recent call last):
  File "unimake.py", line 197, in <module>
    main()
  File "unimake.py", line 141, in main
    imp.load_source("build", args.file)
  File "makefile.uni.py", line 42, in <module>
    from unibuild.projects import sevenzip, qt5, boost, zlib, python, sip
  File "C:\Users\Rob\Documents\Projects\modorganizer\unibuild\projects\boost.py", line 4, in <module>
    from unibuild.projects import python
  File "C:\Users\Rob\Documents\Projects\modorganizer\unibuild\projects\python.py", line 71, in <module>
    .depend(build.Run(r"Tools\buildbot\external-common.bat", environment=python_environment())
  File "C:\Users\Rob\Documents\Projects\modorganizer\unibuild\projects\python.py", line 32, in python_environment
    result['Path'] += ";" + os.path.dirname(config['paths']['svn'])
KeyError: 'Path'
```
# Possible correction

On my installation, the correct key is 'PATH'.  Corrected by using:

```
def python_environment():
    result = config['__environment'].copy()
    pathKey = 'Path'
    for k in result:
        if k.lower() == 'path':
            pathKey=k
            break
    #print('{} = {}'.format(pathKey,repr(result[pathKey])))
    result[pathKey] += ";" + os.path.dirname(config['paths']['svn'])
    return result
```

**Comment by N3X15** [comment]
Appears to have been fixed recently.
