### ISSUE TITLE
Build process fails to unzip archives

### ISSUE THREAD

**Issue by N3X15** [TanninOne/modorganizer-umbrella#5]
If #4 is resolved using the proposed solution, unimake moves on to try and download grep, and then fails.
# Operating System Information
- Windows 10 Pro x64
- Python 2.7.10 (32-bit)
- 7za 15.09 beta (from chocolatey)
# Error Log

```
C:\Users\Rob\Documents\Projects\modorganizer>python unimake.py -d build
2015-11-13 19:58:48,947 building dependency graph
2015-11-13 19:58:48,993 processing tasks
2015-11-13 19:58:48,994 run task "download grep-2.5.4-bin.zip"
2015-11-13 19:58:48,994 File not yet downloaded: build\downloads\grep-2.5.4-bin.zip
2015-11-13 19:58:48,994 Downloading http://downloads.sourceforge.net/project/gnuwin32/grep/2.5.4/grep-2.5.4-bin.zip to build\downloads\grep-2.5.4-bin.zip

Downloading[==================================================] 100%


2015-11-13 19:58:50,815 Extracting http://downloads.sourceforge.net/project/gnuwin32/grep/2.5.4/grep-2.5.4-bin.zip
2015-11-13 19:58:50,815 Task download grep-2.5.4-bin.zip failed
Traceback (most recent call last):
  File "unimake.py", line 197, in <module>
    main()
  File "unimake.py", line 174, in main
    if task.process(progress):
  File "C:\Users\Rob\Documents\Projects\modorganizer\unibuild\modules\urldownload.py", line 79, in process
    self.extract(archive_file_path, output_file_path, progress)
  File "C:\Users\Rob\Documents\Projects\modorganizer\unibuild\modules\urldownload.py", line 133, in extract
    with zipfile.ZipFile(archive_file) as arch:
  File "C:\Python27\lib\zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "C:\Python27\lib\zipfile.py", line 807, in _RealGetContents
    endrec = _EndRecData(fp)
  File "C:\Python27\lib\zipfile.py", line 218, in _EndRecData
    data = fpin.read()
TypeError: read() takes exactly 2 arguments (1 given)
```
# Notes
- I have not ruled out this being a problem with my Python installation;  However, I have just re-installed it from python.org, and still have the problem.
- Archive is complete and valid, permitting me to open it with 7-zip.

**Comment by friesnadrink** [comment]
Did you ever find a solution to this? I didn't have problem #4, but I am getting the exact same error here. As far as I can tell the only difference is I'm on Windows 7 x64.

I also found the downloaded zip file works just fine if i opened it in Winrar, but I took it a little further and tried manually extracting it to .\build\build\grep-2.5.4-bin which looks to be the location it was trying to extract to. Ran it again, but the script just deleted the folder instead of realizing the job was done.

Since the script is able to recognize the file was already downloaded I tried rezipping the file to see if maybe it just didn't like something about the way it was zipped, but got the failed to unzip error anyway.

**Comment by TanninOne** [comment]
This problem is caused by the ProgressFile wrapper implementing the read function according to the function documentation instead of its actual signature.
I do have a fix but not jet committed

**Comment by friesnadrink** [comment]
Thanks for the response. I was able to figure out how to remove the ProgressFile wrapper on the 3 file types that use it and now it is able to extract correctly.

**Comment by BrysonZimmerman** [comment]
Have issue. Can confirm. 

So far I've worked around by downloading the files individually and creating x_download_complete txt files in the progress folder because I don't quite understand python.

**Comment by N3X15** [comment]
Looks like it's been fixed recently.
